name: ae
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.11
  - numpy>=1.24
  - pyyaml>=6.0
  - pytorch>=2.0
  - torchvision
  - torchaudio
  - glfw>=2.6
  - pip:
    - PyOpenGL>=3.1.0
    - PyOpenGL-accelerate>=3.1.0
  - pytest>=7.4
  - pytest-benchmark>=4.0
  - h5py>=3.8
